server:
  port: 8090

spring:
  datasource:
    url:  jdbc:mysql://47.116.133.131:3306/wms?useUnicode=true&characterEncoding=utf-8&useSSL=false&ServerTimezone=GMT%12B8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: hjx00188

